
### Registrar un usuario
POST  http://localhost:3004/usuarios/register
Content-Type: application/json

{
    "nombre": "usuario",
    "password": "prueba123",
    "permisos": "ADMIN",
    "ventaRapida": 123
}

### Loguear un usuario
POST  http://localhost:3004/usuarios/login
Content-Type: application/json

{
    "nombre": "Titox",
    "password": "test1234"
}

### Conseguir info del usuario
GET http://localhost:3004/usuarios/get-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTQ0NTk2NjAsImV4cCI6MTYxNDQ1OTk2MCwiYXVkIjoiY2MyMDFlMGYtOTJmZS00MGY2LWJlOGUtMmNhYzI1NWM1ZDFiIiwiaXNzIjoicnRkZXZlbG9wbWVudC5jb20uYXIifQ.uZctZDJ6SMQ-50Ey6l6RaGXj6fWEz9sUp-AoZPLF50M

### Crear Proveedor
POST http://localhost:3004/proveedores/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTM5NjcyNjIsImV4cCI6MTYxMzk2NzU2MiwiYXVkIjoiY2MyMDFlMGYtOTJmZS00MGY2LWJlOGUtMmNhYzI1NWM1ZDFiIiwiaXNzIjoicnRkZXZlbG9wbWVudC5jb20uYXIifQ.fPYue0Ae6mjYATH_d5fS22FI299WUV3S2YTchSH6JLY
Content-Type: application/json

{
   "codigoInterno": "es",
    "nombre": "El sembrador SRL",
    "email": "sembrame@esta.com",
    "telefono": "343-1234565",
    "descripcion": "Vendemos alcohol " 
}

### Crear data falsa
GET http://localhost:3004/proveedores/bulk 

### Crear Producto
POST http://localhost:3004/productos/create
Content-Type: application/json

{ 
    "codigoInterno": "adadaa",
    "codigoPaquete": "asdfug12uf1",
    "ubicacion": "PROVEEDOR",
    "nombre": "termo",
    "marca": "luzmilagro",
    "descripcion": "acero",
    "alertaMin": "3",
    "alertaMax": "5",
    "estado": "BUENO",
    "precio": "100",
    "precioVenta":"101",
    "cantidad": "12",
    "proveedorId": "8817d876-ce74-44cb-9aab-6013d7b49652"
}

### Get All
GET http://localhost:3004/productos/getall