
### Registrar un usuario
POST  http://localhost:3004/usuarios/register
Content-Type: application/json

{
    "nombre": "Titox",
    "password": "bigshop",
    "permisos": "MASTER",
    "ventaRapida": 422
}

### Crear Proveedores falsos
GET http://localhost:3004/proveedores/bulk 

### Crear Rubros iniciales
POST http://localhost:3004/rubros/inicializar